# Porta da API
server.port=8080

# Conexão com o MySQL local
# Troque a senha abaixo pela senha do seu MySQL Workbench.
spring.datasource.url=jdbc:mysql://localhost:3306/atividades_complementares?useSSL=false&serverTimezone=America/Recife&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SUA_SENHA_AQUI

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Não deixar o Spring apagar/criar tabelas sozinho.
# As tabelas serão criadas pelo arquivo sql/schema.sql no MySQL Workbench.
spring.sql.init.mode=never

# Mostra erros de forma mais clara durante o desenvolvimento
server.error.include-message=always
server.error.include-binding-errors=always
